"""
train_ppo.py -- PPO training script for Objective 1 (MM845): learning to
edit a Coxeter diagram, one (pair, label) at a time, into a spherical one.

This is a plain script run from a terminal:

    $ python -m src.train_ppo --total-timesteps 2000000

never executed from inside a notebook -- Diretrizes.txt reserves the
notebook (notebooks/02_train_rl.ipynb) for loading a finished checkpoint
and demonstrating results via analyze.py, not for running the training
loop. Checkpoints and the training log are written to `results/`, which is
`.gitignore`d (TutorialAmbiente.md, section 6.11): they are meant to be
regenerated by re-running this script, not versioned.

Curriculum over N
------------------
The RL model has a fixed maximum size N_MAX = 8 (env.py), but training
does not sample n_active uniformly over the full range from the start:
for stability, the agent first learns on the smallest, easiest instances
and only later graduates to larger ones. Concretely, `CURRICULUM_STAGES`
below is an increasing sequence of vertex-count sets

    (3, 4, 5)  ->  (3, 4, 5, 6)  ->  (3, 4, 5, 6, 7)  ->  (3, 4, 5, 6, 7, 8)

n_active is sampled UNIFORMLY from whichever set is current (env.py's
`active_ns`). A stage transition is triggered by PERFORMANCE, not by a
fixed timestep budget: once the rolling mean success rate over the last
`curriculum_window_updates` PPO updates clears
`curriculum_success_threshold` (and at least `curriculum_min_updates_per_stage`
updates have happened in the current stage, so a lucky early streak can't
trigger an instant promotion off a handful of noisy episodes), the agent
advances to the next stage and the rolling window resets. Earlier stages'
vertex counts are never dropped -- each stage's set is a superset of the
previous one -- so the agent keeps practising on easy instances even after
graduating, rather than catastrophically forgetting them.

`VecDynkinEnv.set_active_ns` is called on every transition, which changes
what future `reset()`s sample WITHOUT recreating any environment or
touching an episode already in progress (env.py's docstring); the roll-in
across the n_envs sub-environments is therefore gradual, not a hard reset.

Design choices, tracing back to Diretrizes.txt
------------------------------------------------
- Reward: dense, `spherical_margin` of the state after every step, already
  squashed by tanh inside env.py -- not a difference reward, not sparse.
- Action space: one categorical distribution of size C(8,2)*4 = 112
  (env.py), fixed at N_MAX regardless of the current episode's n_active,
  with invalid (padding-touching) actions masked by policy.py -- not a
  per-episode variable-size space, and not a two-stage factorisation.
- Policy: the hand-rolled GNN of policy.py, no external GNN library.
- Priority: training stability above every other consideration. Concretely:
    * advantages are estimated with GAE(lambda) (reduces variance) and
      normalised per update batch,
    * the value loss is PPO2-style clipped, exactly like the policy ratio,
    * gradients are norm-clipped before every optimizer step,
    * a single constant learning rate is used -- no schedule to additionally
      tune,
    * the actor and critic share one GNN trunk and one optimizer, since
      Diretrizes.txt asks for the simplest option whenever a choice does
      not itself bear on stability,
    * the N-curriculum above exists FOR stability: starting directly at
      N_MAX=8 (112-action space, denser cycles) was judged too hard a
      starting distribution; small N first, added back only once
      performance justifies it.

Randomness
----------
All numpy randomness in this file (Adam/torch's own generator aside) flows
through a single explicit `np.random.Generator`, seeded once in `train()`
and threaded down into `ppo_update` for the minibatch shuffle. This matches
the rest of the project's convention (env.py, datagen.py both use
`np.random.default_rng`; TutorialAmbiente.md, section 8, states this is the
"preferred NumPy style" precisely to avoid exactly the kind of hidden,
global mutable state that the legacy `np.random.seed` / `np.random.shuffle`
pair relies on.
"""
from __future__ import annotations

import argparse
import sys
import time
from collections import deque
from dataclasses import asdict, dataclass, field
from pathlib import Path

project_root = Path.cwd().resolve()
while not (project_root / "src").exists() and project_root != project_root.parent:
    project_root = project_root.parent
if not (project_root / "src").exists():
    project_root = Path(__file__).resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

import numpy as np
import torch
import torch.nn as nn

from src.env import N_MAX, VecDynkinEnv
from src.policy import DynkinGNN

# Cumulative curriculum stages over n_active -- see module docstring. Each
# stage's set is a superset of the previous one, and N_MAX=8 always appears
# in the last stage, so the fully-trained agent is evaluated (analyze.py)
# on exactly the same maximum size the project commits to (Diretrizes.txt).
CURRICULUM_STAGES: tuple[tuple[int, ...], ...] = (
    (3, 4, 5),
    (3, 4, 5, 6),
    (3, 4, 5, 6, 7),
    (3, 4, 5, 6, 7, 8),
)


@dataclass
class PPOConfig:
    # Environment
    n_max: int = N_MAX
    dataset: str = "A"  # "A" (uniform) or "B" (sparse) -- see datagen.py
    max_episode_steps: int = 30

    # Curriculum over n_active (see module docstring)
    curriculum_success_threshold: float = 0.7
    curriculum_window_updates: int = 20  # rolling window (in updates) the success rate is averaged over
    curriculum_min_updates_per_stage: int = 20  # floor on updates spent in a stage before a promotion can trigger

    # Rollout collection
    n_envs: int = 16
    rollout_steps: int = 64  # per env, per update; batch size = n_envs * rollout_steps

    # PPO
    total_timesteps: int = 2_000_000
    gamma: float = 0.99
    gae_lambda: float = 0.95
    clip_eps: float = 0.2
    lr: float = 3e-4
    epochs: int = 4
    minibatch_size: int = 256
    entropy_coef: float = 0.01
    value_coef: float = 0.5
    max_grad_norm: float = 0.5

    # Policy architecture
    hidden_dim: int = 64
    label_embed_dim: int = 8
    n_layers: int = 3

    # Bookkeeping
    seed: int = 0
    checkpoint_dir: str = "results"
    checkpoint_every: int = 10  # updates
    log_every: int = 1  # updates


def compute_gae(
    rewards: np.ndarray,
    values: np.ndarray,
    dones: np.ndarray,
    last_values: np.ndarray,
    gamma: float,
    lam: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Generalised Advantage Estimation, vectorised over environments.

    `rewards`, `values`, `dones` have shape (T, n_envs): `dones[t, k]` is 1.0
    iff environment k's episode ended (success or truncation) exactly at
    step t -- VecDynkinEnv auto-resets on that same step, but the identity
    of the resulting "next state" never matters here, because `1 - dones[t]`
    zeroes out the bootstrap term through it regardless of what it is.
    `last_values` (shape (n_envs,)) bootstraps the value of the state
    reached after the very last collected step.
    """
    T, n_envs = rewards.shape
    advantages = np.zeros((T, n_envs), dtype=np.float64)
    lastgaelam = np.zeros(n_envs, dtype=np.float64)
    for t in reversed(range(T)):
        next_values = last_values if t == T - 1 else values[t + 1]
        nonterminal = 1.0 - dones[t]
        delta = rewards[t] + gamma * next_values * nonterminal - values[t]
        lastgaelam = delta + gamma * lam * nonterminal * lastgaelam
        advantages[t] = lastgaelam
    returns = advantages + values
    return advantages, returns


def collect_rollout(
    vec_env: VecDynkinEnv,
    model: DynkinGNN,
    states: np.ndarray,
    n_actives: np.ndarray,
    rollout_steps: int,
) -> tuple[dict, np.ndarray, np.ndarray]:
    """Run `rollout_steps` vectorised steps starting from `states`/`n_actives`
    (the persisted state of every sub-environment, carried over between
    calls so episodes may span rollout boundaries). Returns a dict of numpy
    buffers plus the resulting `(states, n_actives)`, ready to be passed
    back in next time.

    `n_actives` is threaded through exactly like `states`: policy.py cannot
    build its action mask without it, and it cannot be recovered from
    `states` alone (env.py's module docstring) -- so every place `obs_buf`
    is recorded, `n_actives_buf` is recorded alongside it, and every model
    call takes both.
    """
    n_envs = vec_env.n_envs
    n_max = vec_env.envs[0].n_max

    obs_buf = np.zeros((rollout_steps, n_envs, n_max, n_max), dtype=np.int64)
    n_actives_buf = np.zeros((rollout_steps, n_envs), dtype=np.int64)
    actions_buf = np.zeros((rollout_steps, n_envs), dtype=np.int64)
    logprobs_buf = np.zeros((rollout_steps, n_envs), dtype=np.float64)
    values_buf = np.zeros((rollout_steps, n_envs), dtype=np.float64)
    rewards_buf = np.zeros((rollout_steps, n_envs), dtype=np.float64)
    dones_buf = np.zeros((rollout_steps, n_envs), dtype=np.float64)
    margins_buf = np.zeros((rollout_steps, n_envs), dtype=np.float64)
    successes: list[bool] = []

    for t in range(rollout_steps):
        obs_buf[t] = states
        n_actives_buf[t] = n_actives
        with torch.no_grad():
            action_t, logprob_t, _, value_t = model.get_action_and_value(states, n_actives)
        actions_np = action_t.cpu().numpy()

        states, rewards, dones, n_actives, infos = vec_env.step(actions_np)

        actions_buf[t] = actions_np
        logprobs_buf[t] = logprob_t.cpu().numpy()
        values_buf[t] = value_t.cpu().numpy()
        rewards_buf[t] = rewards
        dones_buf[t] = dones.astype(np.float64)
        margins_buf[t] = [info.margin for info in infos]
        for k, done in enumerate(dones):
            if done:
                successes.append(infos[k].success)

    with torch.no_grad():
        _, _, _, last_values_t = model.get_action_and_value(states, n_actives)
    last_values = last_values_t.cpu().numpy()

    batch = dict(
        obs=obs_buf,
        n_actives=n_actives_buf,
        actions=actions_buf,
        logprobs=logprobs_buf,
        values=values_buf,
        rewards=rewards_buf,
        dones=dones_buf,
        margins=margins_buf,
        last_values=last_values,
        successes=successes,
    )
    return batch, states, n_actives


def ppo_update(
    model: DynkinGNN,
    optimizer: torch.optim.Optimizer,
    batch: dict,
    advantages: np.ndarray,
    returns: np.ndarray,
    config: PPOConfig,
    rng: np.random.Generator,
) -> dict[str, float]:
    """One PPO update: `config.epochs` passes over the rollout, in random
    minibatches of size `config.minibatch_size`.

    `rng` is the single explicit `np.random.Generator` threaded down from
    `train()` (see module docstring); it is used for the minibatch shuffle
    below instead of the legacy global `np.random.shuffle`, so the run's
    randomness is fully reproducible from `config.seed` alone and does not
    depend on incidental global RNG state set up (or not) elsewhere.
    """
    device = next(model.parameters()).device
    T, n_envs = batch["actions"].shape
    batch_size = T * n_envs

    obs = batch["obs"].reshape(batch_size, config.n_max, config.n_max)
    n_actives = batch["n_actives"].reshape(-1)
    actions = batch["actions"].reshape(-1)
    old_logprobs = batch["logprobs"].reshape(-1)
    old_values = batch["values"].reshape(-1)
    adv = advantages.reshape(-1).copy()
    ret = returns.reshape(-1)

    # Per-update advantage normalisation -- a standard, cheap variance
    # reducer for the policy gradient (Diretrizes.txt: stability first).
    adv = (adv - adv.mean()) / (adv.std() + 1e-8)

    obs_t = torch.as_tensor(obs, dtype=torch.long, device=device)
    n_actives_t = torch.as_tensor(n_actives, dtype=torch.long, device=device)
    actions_t = torch.as_tensor(actions, dtype=torch.long, device=device)
    old_logprobs_t = torch.as_tensor(old_logprobs, dtype=torch.float32, device=device)
    old_values_t = torch.as_tensor(old_values, dtype=torch.float32, device=device)
    adv_t = torch.as_tensor(adv, dtype=torch.float32, device=device)
    ret_t = torch.as_tensor(ret, dtype=torch.float32, device=device)

    idxs = np.arange(batch_size)
    stats = {"policy_loss": [], "value_loss": [], "entropy": [], "approx_kl": [], "clip_frac": []}

    for _epoch in range(config.epochs):
        rng.shuffle(idxs)
        for start in range(0, batch_size, config.minibatch_size):
            mb_idx = torch.as_tensor(idxs[start : start + config.minibatch_size], device=device)

            # n_actives_t[mb_idx] MUST be the same values used to sample
            # actions_t[mb_idx] originally (see policy.py's
            # get_action_and_value docstring) -- both come from the same
            # rollout buffer row here, so this is automatic, not incidental.
            _, new_logprob, entropy, new_value = model.get_action_and_value(
                obs_t[mb_idx], n_actives_t[mb_idx], action=actions_t[mb_idx]
            )
            log_ratio = new_logprob - old_logprobs_t[mb_idx]
            ratio = log_ratio.exp()

            mb_adv = adv_t[mb_idx]
            surr1 = ratio * mb_adv
            surr2 = torch.clamp(ratio, 1 - config.clip_eps, 1 + config.clip_eps) * mb_adv
            policy_loss = -torch.min(surr1, surr2).mean()

            # PPO2-style clipped value loss: the same trust-region logic
            # applied to the critic, so a single bad minibatch cannot move
            # V(s) arbitrarily far in one step either.
            mb_ret = ret_t[mb_idx]
            mb_old_value = old_values_t[mb_idx]
            value_clipped = mb_old_value + torch.clamp(
                new_value - mb_old_value, -config.clip_eps, config.clip_eps
            )
            value_loss = 0.5 * torch.max(
                (new_value - mb_ret) ** 2, (value_clipped - mb_ret) ** 2
            ).mean()

            entropy_mean = entropy.mean()
            loss = policy_loss + config.value_coef * value_loss - config.entropy_coef * entropy_mean

            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), config.max_grad_norm)
            optimizer.step()

            with torch.no_grad():
                approx_kl = ((ratio - 1) - log_ratio).mean().item()
                clip_frac = ((ratio - 1.0).abs() > config.clip_eps).float().mean().item()

            stats["policy_loss"].append(policy_loss.item())
            stats["value_loss"].append(value_loss.item())
            stats["entropy"].append(entropy_mean.item())
            stats["approx_kl"].append(approx_kl)
            stats["clip_frac"].append(clip_frac)

    return {k: float(np.mean(v)) for k, v in stats.items()}


def save_checkpoint(
    path: Path,
    model: DynkinGNN,
    optimizer: torch.optim.Optimizer,
    config: PPOConfig,
    total_steps: int,
    stage_idx: int,
) -> None:
    torch.save(
        {
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "config": asdict(config),
            "total_steps": total_steps,
            "stage_idx": stage_idx,
            "active_ns": CURRICULUM_STAGES[stage_idx],
        },
        path,
    )


def train(config: PPOConfig) -> Path:
    torch.manual_seed(config.seed)
    rng = np.random.default_rng(config.seed)  # single source of numpy randomness for this run
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    stage_idx = 0
    vec_env = VecDynkinEnv(
        n_envs=config.n_envs,
        seed=config.seed,
        n_max=config.n_max,
        active_ns=CURRICULUM_STAGES[stage_idx],
        max_steps=config.max_episode_steps,
        dataset=config.dataset,
    )
    states, n_actives = vec_env.reset()

    model = DynkinGNN(
        n_max=config.n_max,
        hidden_dim=config.hidden_dim,
        label_embed_dim=config.label_embed_dim,
        n_layers=config.n_layers,
    ).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=config.lr)

    steps_per_update = config.n_envs * config.rollout_steps
    n_updates = max(1, config.total_timesteps // steps_per_update)

    checkpoint_dir = Path(config.checkpoint_dir)
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    log_timesteps, log_reward, log_margin, log_success, log_stage = [], [], [], [], []
    total_steps = 0
    t_start = time.time()

    # Curriculum bookkeeping: a rolling window of per-update success rates
    # for the CURRENT stage only (cleared on every transition), plus a
    # count of updates spent in the current stage (the floor below which a
    # promotion cannot trigger, however good the rolling mean looks).
    success_window: deque[float] = deque(maxlen=config.curriculum_window_updates)
    updates_in_stage = 0

    for update in range(1, n_updates + 1):
        batch, states, n_actives = collect_rollout(vec_env, model, states, n_actives, config.rollout_steps)
        total_steps += steps_per_update

        advantages, returns = compute_gae(
            batch["rewards"],
            batch["values"],
            batch["dones"],
            batch["last_values"],
            config.gamma,
            config.gae_lambda,
        )
        stats = ppo_update(model, optimizer, batch, advantages, returns, config, rng)

        mean_reward = float(batch["rewards"].mean())
        mean_margin = float(batch["margins"].mean())
        success_rate = float(np.mean(batch["successes"])) if batch["successes"] else float("nan")

        log_timesteps.append(total_steps)
        log_reward.append(mean_reward)
        log_margin.append(mean_margin)
        log_success.append(success_rate)
        log_stage.append(stage_idx)

        # Curriculum: advance to the next stage once the rolling mean
        # success rate clears the threshold AND the current stage has run
        # for at least curriculum_min_updates_per_stage updates. An update
        # with no completed episode (success_rate is nan, possible early
        # on with long episodes) contributes 0.0 to the window rather than
        # being skipped -- skipping would let a stalled agent (never
        # finishing an episode) coast on an empty, vacuously-passing window.
        success_window.append(0.0 if np.isnan(success_rate) else success_rate)
        updates_in_stage += 1
        can_promote = stage_idx < len(CURRICULUM_STAGES) - 1
        window_full = len(success_window) == success_window.maxlen
        if (
            can_promote
            and updates_in_stage >= config.curriculum_min_updates_per_stage
            and window_full
            and float(np.mean(success_window)) >= config.curriculum_success_threshold
        ):
            stage_idx += 1
            vec_env.set_active_ns(CURRICULUM_STAGES[stage_idx])
            print(
                f"  >>> curriculum: promoted to stage {stage_idx} "
                f"(active_ns={CURRICULUM_STAGES[stage_idx]}) after {updates_in_stage} updates, "
                f"rolling success rate {np.mean(success_window):.3f}"
            )
            success_window.clear()
            updates_in_stage = 0

        if update % config.log_every == 0:
            elapsed = time.time() - t_start
            print(
                f"update {update:>5}/{n_updates}  steps={total_steps:>10,}  "
                f"stage={stage_idx} active_ns={CURRICULUM_STAGES[stage_idx]}  "
                f"reward={mean_reward:+.3f}  margin={mean_margin:+.3f}  "
                f"success_rate={success_rate:.3f}  "
                f"policy_loss={stats['policy_loss']:+.4f}  value_loss={stats['value_loss']:.4f}  "
                f"entropy={stats['entropy']:.3f}  approx_kl={stats['approx_kl']:.4f}  "
                f"clip_frac={stats['clip_frac']:.3f}  ({elapsed:.1f}s elapsed)"
            )

        if update % config.checkpoint_every == 0 or update == n_updates:
            save_checkpoint(
                checkpoint_dir / f"checkpoint_step_{total_steps}.pt", model, optimizer, config, total_steps, stage_idx
            )
            save_checkpoint(
                checkpoint_dir / "checkpoint_latest.pt", model, optimizer, config, total_steps, stage_idx
            )

    log_path = checkpoint_dir / "train_log.npz"
    np.savez(
        log_path,
        timesteps=np.array(log_timesteps),
        reward=np.array(log_reward),
        margin=np.array(log_margin),
        success_rate=np.array(log_success),
        stage=np.array(log_stage),
    )
    print(f"Training log saved to {log_path}")
    return checkpoint_dir / "checkpoint_latest.pt"


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Train PPO on Objective 1 (spherical Coxeter diagrams).")
    p.add_argument("--total-timesteps", type=int, default=PPOConfig.total_timesteps)
    p.add_argument("--n-envs", type=int, default=PPOConfig.n_envs)
    p.add_argument("--rollout-steps", type=int, default=PPOConfig.rollout_steps)
    p.add_argument("--dataset", type=str, default=PPOConfig.dataset, choices=["A", "B"])
    p.add_argument("--max-episode-steps", type=int, default=PPOConfig.max_episode_steps)
    p.add_argument("--lr", type=float, default=PPOConfig.lr)
    p.add_argument("--seed", type=int, default=PPOConfig.seed)
    p.add_argument("--checkpoint-dir", type=str, default=PPOConfig.checkpoint_dir)
    p.add_argument(
        "--curriculum-success-threshold", type=float, default=PPOConfig.curriculum_success_threshold
    )
    p.add_argument(
        "--curriculum-window-updates", type=int, default=PPOConfig.curriculum_window_updates
    )
    p.add_argument(
        "--curriculum-min-updates-per-stage", type=int, default=PPOConfig.curriculum_min_updates_per_stage
    )
    return p.parse_args()


if __name__ == "__main__":
    args = parse_args()
    config = PPOConfig(
        total_timesteps=args.total_timesteps,
        n_envs=args.n_envs,
        rollout_steps=args.rollout_steps,
        dataset=args.dataset,
        max_episode_steps=args.max_episode_steps,
        lr=args.lr,
        seed=args.seed,
        checkpoint_dir=args.checkpoint_dir,
        curriculum_success_threshold=args.curriculum_success_threshold,
        curriculum_window_updates=args.curriculum_window_updates,
        curriculum_min_updates_per_stage=args.curriculum_min_updates_per_stage,
    )
    train(config)
