"""
train_ppo.py -- PPO training script for Objective 1 (MM845): learning to
edit a Coxeter diagram, one (pair, label) at a time, into a spherical one.

This is a plain script run from a terminal:

    $ python -m src.train_ppo --total-timesteps 2000000

never executed from inside a notebook -- Diretrizes.txt reserves the
notebook (notebooks/02_train_rl.ipynb) for loading a finished checkpoint
and demonstrating results via analyze.py, not for running the training
loop. Checkpoints and the training log are written to `results/`, which is
`.gitignore`d (TutorialAmbiente.md, section 6.11): they are meant to be
regenerated by re-running this script, not versioned.

Design choices, tracing back to Diretrizes.txt
------------------------------------------------
- Reward: dense, `spherical_margin` of the state after every step, already
  squashed by tanh inside env.py -- not a difference reward, not sparse.
- Action space: one categorical distribution of size C(8,2)*4 = 112
  (env.py), not a two-stage factorisation.
- Policy: the hand-rolled GNN of policy.py, no external GNN library.
- Priority: training stability above every other consideration. Concretely:
    * advantages are estimated with GAE(lambda) (reduces variance) and
      normalised per update batch,
    * the value loss is PPO2-style clipped, exactly like the policy ratio,
    * gradients are norm-clipped before every optimizer step,
    * a single constant learning rate is used -- no schedule to additionally
      tune,
    * the actor and critic share one GNN trunk and one optimizer, since
      Diretrizes.txt asks for the simplest option whenever a choice does
      not itself bear on stability.

Randomness
----------
All numpy randomness in this file (Adam/torch's own generator aside) flows
through a single explicit `np.random.Generator`, seeded once in `train()`
and threaded down into `ppo_update` for the minibatch shuffle. This matches
the rest of the project's convention (env.py, datagen.py both use
`np.random.default_rng`; TutorialAmbiente.md, section 8, states this is the
"preferred NumPy style" precisely to avoid exactly the kind of hidden,
global mutable state that the legacy `np.random.seed` / `np.random.shuffle`
pair relies on.
"""
from __future__ import annotations

import argparse
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path

project_root = Path.cwd().resolve()
while not (project_root / "src").exists() and project_root != project_root.parent:
    project_root = project_root.parent
if not (project_root / "src").exists():
    project_root = Path(__file__).resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

import numpy as np
import torch
import torch.nn as nn

from src.env import N_DEFAULT, VecDynkinEnv
from src.policy import DynkinGNN


@dataclass
class PPOConfig:
    # Environment
    n: int = N_DEFAULT
    dataset: str = "A"  # "A" (uniform) or "B" (sparse) -- see datagen.py
    max_episode_steps: int = 30

    # Rollout collection
    n_envs: int = 16
    rollout_steps: int = 64  # per env, per update; batch size = n_envs * rollout_steps

    # PPO
    total_timesteps: int = 2_000_000
    gamma: float = 0.99
    gae_lambda: float = 0.95
    clip_eps: float = 0.2
    lr: float = 3e-4
    epochs: int = 4
    minibatch_size: int = 256
    entropy_coef: float = 0.01
    value_coef: float = 0.5
    max_grad_norm: float = 0.5

    # Policy architecture
    hidden_dim: int = 64
    label_embed_dim: int = 8
    n_layers: int = 3

    # Bookkeeping
    seed: int = 0
    checkpoint_dir: str = "results"
    checkpoint_every: int = 10  # updates
    log_every: int = 1  # updates


def compute_gae(
    rewards: np.ndarray,
    values: np.ndarray,
    dones: np.ndarray,
    last_values: np.ndarray,
    gamma: float,
    lam: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Generalised Advantage Estimation, vectorised over environments.

    `rewards`, `values`, `dones` have shape (T, n_envs): `dones[t, k]` is 1.0
    iff environment k's episode ended (success or truncation) exactly at
    step t -- VecDynkinEnv auto-resets on that same step, but the identity
    of the resulting "next state" never matters here, because `1 - dones[t]`
    zeroes out the bootstrap term through it regardless of what it is.
    `last_values` (shape (n_envs,)) bootstraps the value of the state
    reached after the very last collected step.
    """
    T, n_envs = rewards.shape
    advantages = np.zeros((T, n_envs), dtype=np.float64)
    lastgaelam = np.zeros(n_envs, dtype=np.float64)
    for t in reversed(range(T)):
        next_values = last_values if t == T - 1 else values[t + 1]
        nonterminal = 1.0 - dones[t]
        delta = rewards[t] + gamma * next_values * nonterminal - values[t]
        lastgaelam = delta + gamma * lam * nonterminal * lastgaelam
        advantages[t] = lastgaelam
    returns = advantages + values
    return advantages, returns


def collect_rollout(
    vec_env: VecDynkinEnv, model: DynkinGNN, states: np.ndarray, rollout_steps: int
) -> tuple[dict, np.ndarray]:
    """Run `rollout_steps` vectorised steps starting from `states` (the
    persisted state of every sub-environment, carried over between calls so
    episodes may span rollout boundaries). Returns a dict of numpy buffers
    plus the resulting `states`, ready to be passed back in next time."""
    n_envs = vec_env.n_envs
    n = vec_env.envs[0].n

    obs_buf = np.zeros((rollout_steps, n_envs, n, n), dtype=np.int64)
    actions_buf = np.zeros((rollout_steps, n_envs), dtype=np.int64)
    logprobs_buf = np.zeros((rollout_steps, n_envs), dtype=np.float64)
    values_buf = np.zeros((rollout_steps, n_envs), dtype=np.float64)
    rewards_buf = np.zeros((rollout_steps, n_envs), dtype=np.float64)
    dones_buf = np.zeros((rollout_steps, n_envs), dtype=np.float64)
    margins_buf = np.zeros((rollout_steps, n_envs), dtype=np.float64)
    successes: list[bool] = []

    for t in range(rollout_steps):
        obs_buf[t] = states
        with torch.no_grad():
            action_t, logprob_t, _, value_t = model.get_action_and_value(states)
        actions_np = action_t.cpu().numpy()

        states, rewards, dones, infos = vec_env.step(actions_np)

        actions_buf[t] = actions_np
        logprobs_buf[t] = logprob_t.cpu().numpy()
        values_buf[t] = value_t.cpu().numpy()
        rewards_buf[t] = rewards
        dones_buf[t] = dones.astype(np.float64)
        margins_buf[t] = [info.margin for info in infos]
        for k, done in enumerate(dones):
            if done:
                successes.append(infos[k].success)

    with torch.no_grad():
        _, _, _, last_values_t = model.get_action_and_value(states)
    last_values = last_values_t.cpu().numpy()

    batch = dict(
        obs=obs_buf,
        actions=actions_buf,
        logprobs=logprobs_buf,
        values=values_buf,
        rewards=rewards_buf,
        dones=dones_buf,
        margins=margins_buf,
        last_values=last_values,
        successes=successes,
    )
    return batch, states


def ppo_update(
    model: DynkinGNN,
    optimizer: torch.optim.Optimizer,
    batch: dict,
    advantages: np.ndarray,
    returns: np.ndarray,
    config: PPOConfig,
    rng: np.random.Generator,
) -> dict[str, float]:
    """One PPO update: `config.epochs` passes over the rollout, in random
    minibatches of size `config.minibatch_size`.

    `rng` is the single explicit `np.random.Generator` threaded down from
    `train()` (see module docstring); it is used for the minibatch shuffle
    below instead of the legacy global `np.random.shuffle`, so the run's
    randomness is fully reproducible from `config.seed` alone and does not
    depend on incidental global RNG state set up (or not) elsewhere.
    """
    device = next(model.parameters()).device
    T, n_envs = batch["actions"].shape
    batch_size = T * n_envs

    obs = batch["obs"].reshape(batch_size, config.n, config.n)
    actions = batch["actions"].reshape(-1)
    old_logprobs = batch["logprobs"].reshape(-1)
    old_values = batch["values"].reshape(-1)
    adv = advantages.reshape(-1).copy()
    ret = returns.reshape(-1)

    # Per-update advantage normalisation -- a standard, cheap variance
    # reducer for the policy gradient (Diretrizes.txt: stability first).
    adv = (adv - adv.mean()) / (adv.std() + 1e-8)

    obs_t = torch.as_tensor(obs, dtype=torch.long, device=device)
    actions_t = torch.as_tensor(actions, dtype=torch.long, device=device)
    old_logprobs_t = torch.as_tensor(old_logprobs, dtype=torch.float32, device=device)
    old_values_t = torch.as_tensor(old_values, dtype=torch.float32, device=device)
    adv_t = torch.as_tensor(adv, dtype=torch.float32, device=device)
    ret_t = torch.as_tensor(ret, dtype=torch.float32, device=device)

    idxs = np.arange(batch_size)
    stats = {"policy_loss": [], "value_loss": [], "entropy": [], "approx_kl": [], "clip_frac": []}

    for _epoch in range(config.epochs):
        rng.shuffle(idxs)
        for start in range(0, batch_size, config.minibatch_size):
            mb_idx = torch.as_tensor(idxs[start : start + config.minibatch_size], device=device)

            _, new_logprob, entropy, new_value = model.get_action_and_value(
                obs_t[mb_idx], action=actions_t[mb_idx]
            )
            log_ratio = new_logprob - old_logprobs_t[mb_idx]
            ratio = log_ratio.exp()

            mb_adv = adv_t[mb_idx]
            surr1 = ratio * mb_adv
            surr2 = torch.clamp(ratio, 1 - config.clip_eps, 1 + config.clip_eps) * mb_adv
            policy_loss = -torch.min(surr1, surr2).mean()

            # PPO2-style clipped value loss: the same trust-region logic
            # applied to the critic, so a single bad minibatch cannot move
            # V(s) arbitrarily far in one step either.
            mb_ret = ret_t[mb_idx]
            mb_old_value = old_values_t[mb_idx]
            value_clipped = mb_old_value + torch.clamp(
                new_value - mb_old_value, -config.clip_eps, config.clip_eps
            )
            value_loss = 0.5 * torch.max(
                (new_value - mb_ret) ** 2, (value_clipped - mb_ret) ** 2
            ).mean()

            entropy_mean = entropy.mean()
            loss = policy_loss + config.value_coef * value_loss - config.entropy_coef * entropy_mean

            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), config.max_grad_norm)
            optimizer.step()

            with torch.no_grad():
                approx_kl = ((ratio - 1) - log_ratio).mean().item()
                clip_frac = ((ratio - 1.0).abs() > config.clip_eps).float().mean().item()

            stats["policy_loss"].append(policy_loss.item())
            stats["value_loss"].append(value_loss.item())
            stats["entropy"].append(entropy_mean.item())
            stats["approx_kl"].append(approx_kl)
            stats["clip_frac"].append(clip_frac)

    return {k: float(np.mean(v)) for k, v in stats.items()}


def save_checkpoint(
    path: Path, model: DynkinGNN, optimizer: torch.optim.Optimizer, config: PPOConfig, total_steps: int
) -> None:
    torch.save(
        {
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "config": asdict(config),
            "total_steps": total_steps,
        },
        path,
    )


def train(config: PPOConfig) -> Path:
    torch.manual_seed(config.seed)
    rng = np.random.default_rng(config.seed)  # single source of numpy randomness for this run
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    vec_env = VecDynkinEnv(
        n_envs=config.n_envs,
        seed=config.seed,
        n=config.n,
        max_steps=config.max_episode_steps,
        dataset=config.dataset,
    )
    states = vec_env.reset()

    model = DynkinGNN(
        n=config.n,
        hidden_dim=config.hidden_dim,
        label_embed_dim=config.label_embed_dim,
        n_layers=config.n_layers,
    ).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=config.lr)

    steps_per_update = config.n_envs * config.rollout_steps
    n_updates = max(1, config.total_timesteps // steps_per_update)

    checkpoint_dir = Path(config.checkpoint_dir)
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    log_timesteps, log_reward, log_margin, log_success = [], [], [], []
    total_steps = 0
    t_start = time.time()

    for update in range(1, n_updates + 1):
        batch, states = collect_rollout(vec_env, model, states, config.rollout_steps)
        total_steps += steps_per_update

        advantages, returns = compute_gae(
            batch["rewards"],
            batch["values"],
            batch["dones"],
            batch["last_values"],
            config.gamma,
            config.gae_lambda,
        )
        stats = ppo_update(model, optimizer, batch, advantages, returns, config, rng)

        mean_reward = float(batch["rewards"].mean())
        mean_margin = float(batch["margins"].mean())
        success_rate = float(np.mean(batch["successes"])) if batch["successes"] else float("nan")

        log_timesteps.append(total_steps)
        log_reward.append(mean_reward)
        log_margin.append(mean_margin)
        log_success.append(success_rate)

        if update % config.log_every == 0:
            elapsed = time.time() - t_start
            print(
                f"update {update:>5}/{n_updates}  steps={total_steps:>10,}  "
                f"reward={mean_reward:+.3f}  margin={mean_margin:+.3f}  "
                f"success_rate={success_rate:.3f}  "
                f"policy_loss={stats['policy_loss']:+.4f}  value_loss={stats['value_loss']:.4f}  "
                f"entropy={stats['entropy']:.3f}  approx_kl={stats['approx_kl']:.4f}  "
                f"clip_frac={stats['clip_frac']:.3f}  ({elapsed:.1f}s elapsed)"
            )

        if update % config.checkpoint_every == 0 or update == n_updates:
            save_checkpoint(
                checkpoint_dir / f"checkpoint_step_{total_steps}.pt", model, optimizer, config, total_steps
            )
            save_checkpoint(
                checkpoint_dir / "checkpoint_latest.pt", model, optimizer, config, total_steps
            )

    log_path = checkpoint_dir / "train_log.npz"
    np.savez(
        log_path,
        timesteps=np.array(log_timesteps),
        reward=np.array(log_reward),
        margin=np.array(log_margin),
        success_rate=np.array(log_success),
    )
    print(f"Training log saved to {log_path}")
    return checkpoint_dir / "checkpoint_latest.pt"


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Train PPO on Objective 1 (spherical Coxeter diagrams).")
    p.add_argument("--total-timesteps", type=int, default=PPOConfig.total_timesteps)
    p.add_argument("--n-envs", type=int, default=PPOConfig.n_envs)
    p.add_argument("--rollout-steps", type=int, default=PPOConfig.rollout_steps)
    p.add_argument("--dataset", type=str, default=PPOConfig.dataset, choices=["A", "B"])
    p.add_argument("--max-episode-steps", type=int, default=PPOConfig.max_episode_steps)
    p.add_argument("--lr", type=float, default=PPOConfig.lr)
    p.add_argument("--seed", type=int, default=PPOConfig.seed)
    p.add_argument("--checkpoint-dir", type=str, default=PPOConfig.checkpoint_dir)
    return p.parse_args()


if __name__ == "__main__":
    args = parse_args()
    config = PPOConfig(
        total_timesteps=args.total_timesteps,
        n_envs=args.n_envs,
        rollout_steps=args.rollout_steps,
        dataset=args.dataset,
        max_episode_steps=args.max_episode_steps,
        lr=args.lr,
        seed=args.seed,
        checkpoint_dir=args.checkpoint_dir,
    )
    train(config)
